docs/explanation/index.md
docs/tutorials/content-collection/content-collection.md
docs/tutorials/index.md
mkdocs.yml

Adding a section for contributor content to the documentation and a few small fixes.

docs: adding contributor content section

---

mkdocs.yml

fixing mkdocs because CI failed

fixing mkdocs because CI failed

---

docs/reference/privacy/index.md

Closes # 
- [ x] My pull request adheres to the code style of this project
- [x ] I have updated the documentation as required

feat: added privacy policy

---

docs/getting-started/getting-started.md
docs/getting-started/installation.md

* Add a missing link for the OpenAI account page.
* Fixes small nits for markdown linting (only for the getting started guide).
None

docs: fix getting started

---

docs/getting-started/installation.md

Closes #14 
Add installation steps using rpm, deb, apk

docs: add installtion steps using rpm, deb, apk

---

LICENSE

this PR will contribute to closing https://github.com/k8sgpt-ai/k8sgpt/issues/341 once all checkboxes are ticked for all repos in the org.
This PR is to update the license of this repo to Apache2 which is required for our sandbox application and it will be consistent across all of our repos

chore: update to Apache2 license

---

docs/getting-started/in-cluster-operator.md
mkdocs.yml

Closes # 
- [x ] I have updated the documentation as required

feat: operator getting started

---

docs/reference/guidelines/guidelines.md

Typo fixed in `guidelines.md`.

fix: typo in guidelines.md

---

.codespellignore
.github/workflows/typos.yml
Makefile
README.md
docs/getting-started/in-cluster-operator.md
docs/reference/cli/index.md
docs/reference/guidelines/community.md
docs/reference/guidelines/guidelines.md
mkdocs.yml

This PR adds 
- a typo workflow check for every PR
- fixes typos in the docs

fix: typos

---

docs/tutorials/content-collection/content-collection.md

Add [K8sGPT + LocalAI: Unlock Kubernetes superpowers for free!](https://itnext.io/k8sgpt-localai-unlock-kubernetes-superpowers-for-free-584790de9b65) to the content collection.
Also, add an additional newline to hopefully fix the following rendering issue:

docs: add blog to content collection

---

docs/tutorials/content-collection/content-collection.md

Added my blog [K8sGPT: The Ultimate Tool for Kubernetes Scanning](https://blog.wemakedevs.org/k8sgpt) to the content-collection.

docs: add blog to content-collection

---

docs/getting-started/getting-started.md
docs/reference/cli/filters.md
docs/reference/cli/index.md

Link k8sgpt-ai/k8sgpt/issues/409

docs: Prefer analyze over analyse

---

docs/getting-started/getting-started.md
docs/reference/cli/index.md

Closes # 
Fixed the wrapper around the k8sgpt text and removed stale spacing for maintaining the consistency.
closes #34

fix: k8sgpt wrapper and consistency fixed

---

docs/getting-started/in-cluster-operator.md

Adding a message to point people to add the operator version based on the current release.

fix: operator version to update

---

docs/reference/guidelines/privacy.md

Closes # 
just fixed a typo concerning the anonymize parameter

flag is anonymize not anonymise

---

docs/reference/operator/advanced-installation.md
mkdocs.yml

Adding ArgoCD Application file for the K8sGPT Operator.

feat: adding ArgoCD installation option

---

docs/reference/guidelines/privacy.md
docs/reference/operator/advanced-installation.md
docs/reference/operator/overview.md
mkdocs.yml

Closes #39  
fixes the hyperlink for the values.yml file

Fixed hyperlink mismatch

---

docs/reference/cli/filters.md

fix small typos

---

docs/getting-started/getting-started.md

Closes #70
This PR updates the command mentioned in [Getting Started guide](https://docs.k8sgpt.ai/getting-started/getting-started/) to authenticate k8sgpt with  OpenAI.
**After:**

Update the command in Getting Started to authenticate with OpenAI

---

docs/explanation/index.md
docs/explanation/integrations.md
mkdocs.yml

Closes #56 
- Added explanation for `integration` under explanation.
- Removed the `index.md` file under explanation.
- Included in the `nav` configuration in `mkdocs.yml`

feat: add explanation for integration

---

docs/getting-started/in-cluster-operator.md

Fixes #59 
implement the changes as mention in the issue

docs :Update in-cluster-operator.md

---

docs/explanation/caching.md
mkdocs.yml

Closes #72
Changes made-
- Added explanation for `caching` under explanation section.

feat: add explanation for caching

---

docs/getting-started/Community.md
mkdocs.yml

Closes #80 
added community section to the docs so that the contributors can navigate through the project

added community section to the docs

---

docs/getting-started/Community.md

feat: update Community.md

---

docs/explanation/integrations.md
docs/getting-started/Community.md
docs/getting-started/in-cluster-operator.md
docs/getting-started/installation.md
docs/reference/cli/filters.md
docs/reference/guidelines/guidelines.md
docs/reference/guidelines/privacy.md
docs/reference/operator/advanced-installation.md
docs/reference/providers/backend.md
docs/tutorials/content-collection/content-collection.md
docs/tutorials/index.md
docs/tutorials/playground.md

This pull request addresses various typos and grammatical errors throughout the codebase to enhance readability and maintain consistency. The changes primarily focus on improving the quality of the documentation and ensuring clarity in the project's content.
During my review, I found some spelling mistakes that I fixed in this pull request. If you notice anything else that needs to be changed or have any suggestions, please let me know. I'll make sure to fix them quickly to keep everything consistent with the project's standards. Your feedback is important for keeping the project professional and well-organized.

docs: Some typos and grammar mistakes.

---

docs/reference/providers/backend.md

This pull request add comprehensive documentation for the newly added Hugging Face (new added) provider in this project.
- Added detailed documentation for the Hugging Face provider in the backend.md file.
- Included steps for authentication, configuration, and usage of the Hugging Face backend.
- Provided instructions for obtaining the API key and configuring the backend model.
Merging this PR in one go might be challenging, so please don't hesitate to point out any mistakes or suggest enhancements. Your feedback is greatly appreciated.

docs: add documentation for the newly added hugging face provider

---

docs/reference/cli/index.md
docs/reference/providers/backend.md

Closes # 
The `auth new` has been renamed to `auth add` in https://github.com/k8sgpt-ai/k8sgpt/pull/438
Fix the docs of it.

fix: rename`auth new` to `auth add`

---

docs/reference/providers/backend.md

Closes # 
- Add Ollama to backends 
- fix typo in LocalAI auth

Add Ollama to backends and fix typo in LocalAI

---

docs/build/Dockerfile
docs/tutorials/custom-analyzers.md
mkdocs.yml

feat: tutorial for custom analysis

---

docs/reference/providers/backend.md

Add IBM watsonx ai provider document.
Reference: https://github.com/k8sgpt-ai/k8sgpt/pull/1163

feat: add watsonx ai provider document

---

docs/reference/cli/index.md

Closes #110 
Closes #108 
Fixes examples in the [CLI reference](https://docs.k8sgpt.ai/reference/cli/#additional-commands) for serving and analyzing served requests.
n/a

fix and expand serve/analysis examples

---

docs/getting-started/installation.md

Closes # 
Here I'm adding a section on how to install k8sgpt via glasskube. I have previously reached out to Alex on the matter and hope the section is appropriate. By all means, if any changes need to be made, I'm all ears. 
Additionally, I'm attaching a screenshot to the PR of what the k8sgpt-operator package configuration UI looks like on Glasskube. I haven't added the screenshot to the docs since I was not sure if it is necessary. If need be, let me know and I can add it underneath the installation instructions. 
Thanks a million.

docs: added installation steps for k8sgpt via Glasskube

---

docs/reference/cli/debugging.md
mkdocs.yml

Closes # 
- [x ] My pull request adheres to the code style of this project
- [x ] My code requires changes to the documentation
- [ x] I have updated the documentation as required
- [ x] All the tests have passed

feat: added debugging command reference

---

mkdocs.yml

Closes # 
- [ x] My pull request adheres to the code style of this project
- [x ] My code requires changes to the documentation
- [x ] I have updated the documentation as required
- [x ] All the tests have passed

feat: added quick grafana doc

---

docs/tutorials/custom-rest-backend.md

feat: tutorial for customrest AI backend 

---

docs/tutorials/playground.md

"docs: killercoda name rectified"

---

mkdocs.yml

Closes # 
- [ x] My pull request adheres to the code style of this project
- [x ] My code requires changes to the documentation
- [x ] I have updated the documentation as required
- [ x] All the tests have passed

feat: updated mkdocs.yml

---

docs/getting-started/getting-started.md

fix: Spelling mistake 'killercoda'

---

docs/tutorials/custom-analyzers.md

Update the examples with latest workable code, and elaborate the steps.

docs: fix custom analyzer doc
